version: '3.7'

services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3307
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DB=ticket_db
      - REDIS_HOST=redis
      - ETCD_HOST=etcd
    depends_on:
      - mysql
      - redis
      - etcd

  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ticket_db
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./initialization.sql:/docker-entrypoint-initdb.d/initialization.sql

  redis:
    image: redis:6.0
    ports:
      - "6379:6379"

  etcd:
    image: bitnami/etcd:latest
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
    ports:
      - "2379:2379"

volumes:
  mysql-data:
